version: '3.8'

services:
  wordpress:
    image: wordpress
    restart: always
    expose:
      - 80
    deploy:
      replicas: 2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress_db
      # WP_REDIS_HOST: db_cache
      # WP_REDIS_PORT: 6379
      WORDPRESS_CONFIG_EXTRA: define('WP_REDIS_HOST','db_cache'); define('WP_REDIS_PORT','6379');
    networks:
      - proxy_network
      - db_network
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_network
  db_cache:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379
    volumes:
      - cache:/data
    networks:
      - db_network
  proxy:
    image: nginx:latest
    environment:
      - WP_ADDRESS=wordpress
      - WP_PORT=80
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    networks:
      - proxy_network
    depends_on:
      - wordpress

volumes:
  db:
  cache:


networks:
  proxy_network:
    driver: bridge
  db_network:
    driver: bridge
